import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getCloudflareContext } from "@opennextjs/cloudflare";

import "./globals.css";
import LinkWrapper from "@/components/LinkWrapper";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { env } = await getCloudflareContext({async: true});
	const navigation = await env.prisma_demo_db.prepare('SELECT * FROM Navigation').all();
	console.log('navigation', navigation.results);
	// const navigation = await env.prisma_demo_db.navigation.findMany();
	//console.log(navigation);
	const navItems = [
		{ href: '/', label: 'Home' },
		{ href: '/mylocation', label: 'My Location' },
		{ href: '/about', label: 'About' },
		{ href: '/contact', label: 'Contact' },
	];
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
					<nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-200 shadow-sm">
						<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
							<div className="flex items-center justify-between h-16">
								{/* Logo/Brand */}
								<div className="flex-shrink-0">
									<LinkWrapper href="/" className="flex items-center space-x-2 group">
										<div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-blue-600 rounded-lg flex items-center justify-center transform group-hover:scale-110 transition-transform duration-200">
											<span className="text-white font-bold text-lg">L</span>
										</div>
										<span className="text-xl font-bold bg-gradient-to-r from-blue-600 to-blue-800 bg-clip-text text-transparent">
											LocationApp
										</span>
									</LinkWrapper>
								</div>

								{/* Navigation Links */}
								<div className="hidden md:flex items-center space-x-1">
									{navItems.map((item) => (
										<LinkWrapper
											key={item.href}
											href={item.href}
										>
											{item.label}
										</LinkWrapper>
									))}
								</div>

								{/* Mobile Menu Button */}
								<div className="md:hidden">
									<button
										type="button"
										className="inline-flex items-center justify-center p-2 rounded-md text-gray-700 hover:text-blue-600 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500"
										aria-label="Open main menu"
									>
										<svg
											className="h-6 w-6"
											fill="none"
											viewBox="0 0 24 24"
											stroke="currentColor"
										>
											<path
												strokeLinecap="round"
												strokeLinejoin="round"
												strokeWidth={2}
												d="M4 6h16M4 12h16M4 18h16"
											/>
										</svg>
									</button>
								</div>
							</div>
						</div>

						{/* Mobile Navigation */}
						<div className="md:hidden border-t border-gray-200">
							<div className="px-2 pt-2 pb-3 space-y-1">
								{navItems.map((item) => (
									<LinkWrapper
										key={item.href}
										href={item.href}
									>
										{item.label}
									</LinkWrapper>
								))}
							</div>
						</div>
					</nav>

					{/* Main Content */}
					<main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
						{children}
					</main>
					<footer className="text-center text-sm text-gray-500 py-4">
						<p>© {new Date().getFullYear()} LocationApp. All rights reserved.</p>
					</footer>
				</div>
			</body>
		</html>
	);
}
