import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import RightsReserved from "@/components/RightsReserved";
import Navigation from "@/components/Navigation";
import { Suspense } from "react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
					<Navigation />

					{/* Main Content */}
					<main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
						{children}
					</main>
					<footer className="text-center text-sm text-gray-500 py-4">
						<Suspense fallback={<div>Loading...</div>}>
							<RightsReserved />
						</Suspense>
					</footer>
				</div>
			</body>
		</html>
	);
}
